### ISSUE TITLE
Problem from Godot 3.6

### ISSUE THREAD

**Issue by Firty** [Shin-NiL/Godot-Android-Share-Plugin#25]
Hi... 
I'm having these problems when trying to export. it seems to me that there is a conflict between these two attributes. it's probably very simple to work around this... I even managed to open the .aar file and find these attributes inside the AndroidManifest.xml file. But I don't really know what I should do...

Attribute provider#androidx.core.content.FileProvider from [godot-lib.debug.aar] AndroidManifest.xml:28:13-64
	is also present at [GodotShare.release.aar] AndroidManifest.xml:18:13-51
	Suggestion: add 'tools:replace="android:authorities"' to <provider> element at AndroidManifest.xml:26:9-34:20

	Attribute meta-data#android.support.FILE_PROVIDER_PATHS@resource value=(@xml/godot_provider_paths) from [godot-lib.debug.aar] AndroidManifest.xml:33:17-61
	is also present at [GodotShare.release.aar] AndroidManifest.xml:23:17-60 value=(@xml/file_provider_paths).
	Suggestion: add 'tools:replace="android:resource"' to <meta-data> element at AndroidManifest.xml to override.

**Comment by gumaciel** [comment]
try it:

Add to your AndroidManifest.xml file, inside the application tag:
```xml
    <provider
        android:name="android.support.v4.content.FileProvider"
        android:authorities="${applicationId}.fileprovider"
        android:exported="false"
        android:grantUriPermissions="true"
        tools:replace="android:authorities">
        <meta-data
            android:name="android.support.FILE_PROVIDER_PATHS"
            android:resource="@xml/file_paths"
            tools:replace="android:resource" />
    </provider>
```

**Comment by Firty** [comment]
I had to add xmlns:tools="http://schemas.android.com/tools" at the beginning of the xml but it worked.
