### ISSUE TITLE
Demo don't work in android 5.1 

### ISSUE THREAD

**Issue by git2013vb** [Shin-NiL/Godot-Android-Share-Plugin#3]
Godot 3.2 stable + Debian 10
Hi I tried  the demo in my device but it don't start.
No error messages. Just do nothing. I tried to open the demo from my device with no result.

ps.: I have another android app that work properly but when I add the "android" folder in project it stop working too.
Thank you

**Comment by git2013vb** [comment]
Sorry I forgot to add the sdk path in editor :)

**Comment by git2013vb** [comment]
Hi again :)
I setup sdk properly but still nothing. Here my log from Godot:
![image](https://user-images.githubusercontent.com/13235119/74605858-9f51bb80-50c3-11ea-843a-16191aa39d4a.png)

I even tried another attempt adding android_release.apk and android_debug.apk from android/build/outpits/apk/  as you can see here:
![image](https://user-images.githubusercontent.com/13235119/74605908-066f7000-50c4-11ea-98bc-504109906c50.png)

The demo is reinstalled but it wont run.
Any suggestions? I missed something?

Thank you.

**Comment by Shin-NiL** [comment]
I've tested on my device (Android 9) and is working fine.
You don't use the android_release and android_debug apk files as you're using the custom build option.

Try to redo the procedure step by step.

Another thing you can do is take a look at the log output with adb:
```adb logcat -s godot```

**Comment by git2013vb** [comment]
Thank you for your answer,
I think I found the error.
But how I can resolve it?

```
-------- beginning of /dev/log/main
I/godot   ( 9141): Loading Android module: org/godotengine/godot/GodotShare
E/godot   ( 9141): **ERROR**: Couldn't find singleton for class: org/godotengine/godot/GodotShare.
E/godot   ( 9141):    At: platform/android/java_godot_lib_jni.cpp:691:_initialize_java_modules() - Condition "!singletonClass" is true. Continuing.

Thank you
```

**Comment by Shin-NiL** [comment]
Did you do this?

>drop the share-plugin directory (from the zip package) inside the res://android/ directory on your Godot project.

and selected the "Use Custom Build" at the android export option?

**Comment by git2013vb** [comment]
> Did you do this?
> 
> > drop the share-plugin directory (from the zip package) inside the res://android/ directory on your Godot project.
> 
> and selected the "Use Custom Build" at the android export option?

I did download your project (the whole) and I run your demo . Seems silly but are you telling me that I have to "combine" your demo with your plugin in different way as is now?
If yes I have a question: Why did't you made a complete project in 1 place and the plugin only in another one? :) That's confuse me (maybe not only me I guess)

So, to me, the project was the your plugin root :)
Seems like Chinese boxes lol
