### ISSUE TITLE
Incompatibility with gradle-6.1.1-all.zip

### ISSUE THREAD

**Issue by Montecri** [Shin-NiL/Godot-Android-Share-Plugin#4]
Hello,

Found an incompatibility with gradle-6.1.1-all.zip.

Had to change the following:

GodotShare.java:

//import android.support.v4.content.FileProvider;
import androidx.core.content.FileProvider;

AndroidManifest.conf:

android:name="androidx.core.content.FileProvider"

Thanks.

- Cristiano

**Comment by Shin-NiL** [comment]
Thanks, I'll update the code.

**Comment by mthnzbk** [comment]
[https://ibb.co/Df5JKQN](https://ibb.co/Df5JKQN)
I am using Godot 3.2.1. Godot installs gradle5.1i by default, I think. That's why the compilation fails. Can Godot Engine gradle use the latest version?

**Comment by Montecri** [comment]
> 
> 
> https://ibb.co/Df5JKQN
> I am using Godot 3.2.1. Godot installs gradle5.1i by default, I think. That's why the compilation fails. Can Godot Engine gradle use the latest version?

Perhaps we need something like:

if(VERSION.SDK.equals(<version>)){
import a
} else {
import b
}

To load the appropriate library version.

For now, try to replace androidx.core.content.FileProvider with android.support.v4.content.FileProvider in GodotShare.java

Also, fix similar entry on AndroidManifest.conf.

Hope this helps for now.

**Comment by Shin-NiL** [comment]
I think I'll revert the last commit because as @mthnzbk noted, godot install gradle 5.1.1 by default and this could confuse the user. We could update it later when Godot also does.
