### ISSUE TITLE
How do check if the plugin was loaded?

### ISSUE THREAD

**Issue by guybashan** [Shin-NiL/Godot-Android-Share-Plugin#8]
Usually in Godot modules I use to check if the module is loaded using something like:
`if (Engine.has_singleton("GodotShare"))`

Any way of checking it for this plugib?

**Comment by Shin-NiL** [comment]
The syntax stills the same as in the module. There's no difference in the gdscript side.

**Comment by trollusk** [comment]
Commenting as this comes up when googling for how to check if a plugin is loaded.
`Engine.has_singleton` does not work - it only detects built-in singletons, not autoloads.

The following works:

`Engine.get_main_loop().root.has_node("AutoloadName")`
